import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.variable} h-full antialiased`}>
      <body className="min-h-screen flex flex-col">
        <Providers>
          <Toaster position="top-right" />
          <div className="flex flex-col items-center justify-start py-10 gap-10 flex-1 md:py-20">
            <h1 className="text-2xl text-white font-bold leading-1 md:text-4xl">
              TODO <span className="text-primary">LIST</span>
            </h1>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
